### ISSUE TITLE
3.2.0 breaks API by introducing new MapAccessor::__get() method

### ISSUE THREAD

**Issue by cerlestes** [graphaware/neo4j-php-commons#7]
This broke on our production server yesterday: We're using `graphaware/neo4j-php-client` at `~4.3.0` in our composer.json, but `graphaware/neo4j-common` was updated to `3.2.1`, as the only depency for that package is `^3.0` in `graphaware/neo4j-php-client`. Looking into the issue, we found that an interface (MapAccessor) was changed in `3.2.0`. According to semver, this should have brought the version to `4.0.0` due to changing the API in a non-backwards-compatible way, which would have avoided the issue. Just fyi. Thanks for developping these packages!

**Comment by ikwattro** [comment]
You should upgrade also the client, v4.4.3 is the latest. The __get method in the MapAccessor was upgraded in the same time as in neo4j-common, so 10 days ago.

https://github.com/graphaware/neo4j-php-client/commit/87c419f8c5785ff2eeb0b657ffef7523bfa8b036#diff-a80c5a3d663171654a5c247fb9ab7535R77

On the side note, you are right about the semver here, I should have bumped the version when tagging the PR. I will try to avoid this in the future
